/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/modal`; params?: Router.UnknownInputParams; } | { pathname: `/signin-modal`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/bunsekikun` | `/bunsekikun`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/custom-mode` | `/custom-mode`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/jlpt-study` | `/jlpt-study`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/kana-quiz` | `/kana-quiz`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/vocab-editor` | `/vocab-editor`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/modal`; params?: Router.UnknownOutputParams; } | { pathname: `/signin-modal`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/bunsekikun` | `/bunsekikun`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/custom-mode` | `/custom-mode`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/jlpt-study` | `/jlpt-study`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/kana-quiz` | `/kana-quiz`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/vocab-editor` | `/vocab-editor`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/modal${`?${string}` | `#${string}` | ''}` | `/signin-modal${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/bunsekikun${`?${string}` | `#${string}` | ''}` | `/bunsekikun${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/custom-mode${`?${string}` | `#${string}` | ''}` | `/custom-mode${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/jlpt-study${`?${string}` | `#${string}` | ''}` | `/jlpt-study${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/kana-quiz${`?${string}` | `#${string}` | ''}` | `/kana-quiz${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/vocab-editor${`?${string}` | `#${string}` | ''}` | `/vocab-editor${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/modal`; params?: Router.UnknownInputParams; } | { pathname: `/signin-modal`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/bunsekikun` | `/bunsekikun`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/custom-mode` | `/custom-mode`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/jlpt-study` | `/jlpt-study`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/kana-quiz` | `/kana-quiz`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/vocab-editor` | `/vocab-editor`; params?: Router.UnknownInputParams; };
    }
  }
}
